name: odoo_startkit
description: Flutter CRUD with Odoo_12
publish_to: 'none'
version: 1.0.4+5

environment:
  sdk: ">=2.16.2 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  shared_preferences: 2.0.15
  http: 0.13.4
  uuid: 3.0.6
  flutter_svg: 1.0.3
  dropdown_search: 3.0.1
  photo_view: 0.14.0
  image_picker: 0.8.5+3
  intl: 0.17.0
  pull_to_refresh: 2.0.0
  date_time_picker: 2.1.0
  rotated_corner_decoration: 2.0.0
  file_picker: 4.6.1
  path_provider: 2.0.11
  sqflite: 2.0.2+1
  flutter_offline: 2.1.0
  flutter_spinkit: 5.1.0
  flutter_barcode_scanner: 2.0.0
  geolocator: 9.0.0
  hexcolor: 2.0.7
  package_info_plus: 1.4.2
  percent_indicator: 3.4.0
  onesignal_flutter: 3.4.1
  firebase_core: 1.20.1
  firebase_dynamic_links: 4.3.4
  flutter_phoenix: 1.0.0
  webview_flutter: ^3.0.4
  url_launcher: ^6.1.7
  cached_network_image: ^3.2.0
  icon_badge: ^1.0.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.4
  
flutter:
  uses-material-design: true
  assets:
    - assets/config/
    - assets/langs/
    - assets/avatars/
    - assets/images/
    - assets/images/country/
    - assets/svg/
    - assets/fonts/
    - assets/private_policy/
    - assets/images/iconsMessage/
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-Light.ttf
          weight: 300
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
          weight: 600
